sport_dict = {
        101: "athlétisme",
        102: "sociétés d'aviron",
        103: "badminton",
        105: "basketball",
        106: "boxe ",
        107: "canoë-kayak",
        108: "cyclisme",
        109: "équitation",
        110: "escrime",
        111: "football",
        112: " sports de glace",
        113: "gymnastique ",
        114: "haltérophilie, musculation, force athlétique et culturisme",
        115: "handball",
        116: "hockey",
        117: "judo-jujitsu et disciplines associées",
        118: "lutte",
        119: "natation",
        120: "pentathlon moderne ",
        121: "ski",
        122: "taekwondo et disciplines associées" ,
        123: "tennis",
        124: "tennis de table",
        125: "tir",
        126: "tir à l'arc",
        127: "triathlon",
        128: "voile",
        129: "volley-ball",
        131: "hockey sur glace",
        132: "golf",
        133: "rugby",
        201: "aéromodélisme",
        202: "aéronautique",
        203: "aérostation",
        204: "aïkido, d'aïkibudo et affinitaires",
        205: "aïkido et de budo",
        206: "automobile",
        207: "jeu de balle au tambourin",
        208: "ballon au poing",
        209: "ball-trap et de tir à balle",
        210: "billard",
        211: "boules",
        212: "boxe française, savate et disciplines associées",
        213: "bowling et de sports de quilles",
        214: "char à voile",
        215: "la course camarguaise",
        216: "la course landaise",
        217: "la course d'orientation",
        218: "cyclotourisme",
        219: "danse",
        220: "échecs",
        221: "études et sports sous-marins",
        222: "football américain",
        223: "fighting full contact et disciplines associées",
        224: "giraviation",
        226: "javelot tir sur cible",
        227: "jeu de paume",
        228: "joutes et sauvetage nautique",
        229: "karaté et disciplines associées",
        231: "longue paume",
        232: "la montagne et de l'escalade",
        233: "motocyclisme",
        234: "motonautique",
        235: "muaythaï et disciplines associées",
        237: "parachutisme",
        238: "pêche sportive au coup",
        239: "pêcheurs en mer",
        240: "pêche à la mouche et au lancer",
        241: "pelote basque",
        242: "pétanque et jeu provençal",
        243: "planeur ultra léger motorisé" ,
        244: "pulka et traineau à chiens",
        245: "la randonnée pédestre",
        246: "roller sports",
        248: "rugby à XIII",
        249: "sauvetage et secourisme",
        250: "ski nautique et wake board",
        251: "spéléologie",
        252: "squash",
        253: "surf",
        254: "Wushu Arts énergétiques et martiaux chinois",
        255: "sports de traîneau, de ski pulka et cross canins",
        256: "twirling bâton",
        257: "vol à voile",
        258: "vol libre",
        260: "polo",
        261: "sports de contact et disciplines associées",
        262: "baseball et softball",
        263: "double dutch",
        264: "Fédération Flying Disc France: ",
        401: "clubs alpins et de montagne",
        402: "éducation physique et de gymnastique volontaire",
        403: "sport pour tous",
        404: "la retraite sportive",
        405: "travailliste",
        406: "clubs de la défense",
        407: "nationale en milieu rural",
        408: "sportive et culturelle de France",
        409: "Maccabi ",
        410: "sportive et gymnique du travail (FSGT)",
        411: "sportive de la police nationale",
        413: "Union française des œuvres laïques d'éducation p,hysique (UFOLEP)",
        415: "omnisports des personnels de l'éducation nationa,le de la jeunesse et sports (2 OPEN-JS)",
        417: "Union nationale sportive Léo Lagrange",
        418: "d'entreprise" ,
        420: "Fédération sportive des ASPTT",
        501: "handisport",
        503: "adapté",
        601: "universitaire",
        602: "Union générale sportive de l'enseignement libre",
        603: "Union nationale des clubs universitaires",
        604: "Union nationale scolaire (UNSS)",
        605: "Union sportive de l'enseignement du premier degré"
        }
